name: Flutter CI

on:
  push:
    branches: [ main, ci/**, feature/** ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.4'
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Format check (non-blocking)
        run: dart format --output=none  .
        continue-on-error: true

      - name: Analyze
        run: flutter analyze

      - name: Test
        run: flutter test --coverage

      - name: Build Web (release)
        run: flutter build web --release

      - name: Upload web build artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web
          sssss